name: Multi-stage CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build artifact
        run: |
          echo "BUILD SUCESS" > build.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build.txt
  test:
    runs-on: ubuntu-latest
    need: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Run tests
        run: |
          cat build.txt
        echo "TESTS PASSED"
  
  deploy:
    run-on: ubuntu-latest
    needs: test
    steps:
      - name: Simulated dpeloy
        run: echo "DEPLOY SUCESSS"
